# Install
#    cargo install --force cargo-make cargo-fuzz

[config]
default_to_workspace = false

[tasks.default]
alias = "workflow"

[tasks.workflow]
dependencies = [ "test-all", "format", "clippy", "doc", "fuzz", "mutants" ]

[tasks.test-all]
dependencies = ["test-all-features", "test-nostd" ]

[tasks.test-all-features]
command = "cargo"
args = ["test", "--all-features"]

[tasks.test-nostd]
command = "cargo"
args = ["test", "--no-default-features"]

[tasks.cov]
toolchain = "nightly"
install_crate = "cargo-llvm-cov"
command = "cargo"
# Could add  --branch  (superceded by --mcdc)
# Could add --show-instantiations to show how functions are instantiated
args = [ "llvm-cov", "test", "--show-missing-lines", "--doctests", "--html", "--all-features", "--color=always" ]

[tasks.doc]
command = "cargo"
args = [ "doc", "-p", "rust_intervals" ]

[tasks.fuzz]
dependencies = [ "fuzz_intv", "fuzz_multi" ]

[tasks.fuzz_intv]
toolchain = "nightly"
install_crate = "cargo-fuzz"
command = "cargo"
args = ["fuzz", "run", "fuzz_target_1", "--", "-max_total_time=10", "-max_len=1000"]

[tasks.fuzz_multi]
toolchain = "nightly"
install_crate = "cargo-fuzz"
command = "cargo"
args = ["fuzz", "run", "fuzz_target_multi", "--", "-max_total_time=10", "-max_len=8000"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-features"]

# Find areas in the code that can be modified without impacting any of the tests
[tasks.mutants]
command = "cargo"
args = ["mutants", "--all-features", "--jobs=4"]
