# Install
#    cargo install --force cargo-make cargo-fuzz

[config]
default_to_workspace = false

[tasks.workflow]
dependencies = [ "test", "format", "coverage", "doc", "fuzz" ]

[tasks.test]
dependencies = ["test-default", "test-nostd" ]

[tasks.test-default]
command = "cargo"
args = ["test", "--features=chrono,serde"]

[tasks.test-nostd]
command = "cargo"
args = ["test", "--no-default-features"]

[tasks.coverage]
dependencies = ["codecov-clean"]
env = { "CARGO_INCREMENTAL" = "0", "RUSTFLAGS" = "-Cinstrument-coverage", "LLVM_PROFILE_FILE" = "cargo-test-%p-%m.profraw" }
run_task = "codecov-grcov"

[tasks.codecov-grcov]
dependencies = [ "test" ]
command = "grcov"
args = [".", "-s", ".", "--binary-path", "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/debug/", "-t",  "html", "--branch", "--ignore-not-existing", "-o", "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/debug/coverage/"]

[tasks.codecov-clean]
script_runner = "@shell"
script = "rm -f *.profraw"

[tasks.doc]
command = "cargo"
args = [ "doc" ]

[tasks.fuzz]
toolchain = "nightly"
install_crate = "cargo-fuzz"
command = "cargo"
args = ["fuzz", "run", "fuzz_target_1", "--", "-max_total_time=10", "-max_len=1000"]
